### PR TITLE
! Fix: #197 change terms for JSON fields

### PR DESCRIPTION
**Pull request by dimus**
#197 

Two additional changes we did not talk about --

- remove "n/a" rank
- change id to name_string_id

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
`infragenus` does not change?

**Comment by dimus** [comment]
hm, I just noticed http://www.tdwg.org/fileadmin/_migrated/content_uploads/example_v101.xml

actually give it as InfragenericEpithet, instead of Infragenus

**Comment by dimus** [comment]
I changed infragenus to infrageneric_epithet

**Comment by alexander-myltsev** [comment]
@dimus , please investigate my improvements at https://github.com/GlobalNamesArchitecture/gnparser/pull/212 . If all is OK then squash it please before merge.

**Pull request merged**
