### PR TITLE
= JSON fields documentation

### LINKED ISSUE #36: Make JSON fields table documentation file

### PR DESCRIPTION
**Pull request by dimus**
Fix #36

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
I think it should be placed in the README where all documentation lives. And put extra information on where that JSon comes from.

**Comment by dimus** [comment]
Lets keep it here until we know the place for it in README, then we will move it

**Comment by alexander-myltsev** [comment]
There are bunch of things that are bad:
* every json node has *only one* parent
* there is no `dictionary` notion in json. It is an object 
* it is really easy to lost track on that is nested to what is a plain table approach

I think we should consider using a standard JSon schema way. Take a look at http://json-schema.org/examples.html . WDYT?

**Comment by dimus** [comment]
Take in account the audience who will read the paper. Many of them are biologists, and for them your suggestions would be hard to grasp. 

* We need to explain that the same node might be attached to several types of parents. How would you approach that?
* I chose `dictionary` over `object` or `hash` as it is easier to understand for people who are not avid JSON users.
* Table is more natural for the audience I believe

**Comment by alexander-myltsev** [comment]
OK, good enough for now. We should do it in [a more robust way](https://github.com/GlobalNamesArchitecture/gnparser/issues/157).

**Pull request merged**
