### PR TITLE
Fix #241 garbage to unparsed

### LINKED ISSUE #241: Change `garbage` to more politically correct term
What is a garbage for one might be something importatnt for other. Also sometimes parser puts part of legitimate name into garbage because it of lack of a rule. So we need a better term - `unparsed_tail` may be?

### PR DESCRIPTION
**Pull request by dimus**

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
Where JSON_FIELDS.md goes to now?

**Comment by dimus** [comment]
I removed it, so we do not support JSON documentation in 2 places

**Comment by alexander-myltsev** [comment]
LGTM

**Comment by alexander-myltsev** [comment]
I moved deletion of JSON_FIELDS to another commit.

**Pull request merged**
