### PR TITLE
+ fix normalization for complex uninomials

### LINKED ISSUE #43: Parse names with combinations of uninomials
We have rules for that, but they do not work right now

### PR DESCRIPTION
**Pull request by dimus**
Fix #43

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
@dimus I fixed your commit

You should fix position node name [here](https://github.com/GlobalNamesArchitecture/gnparser/blob/43-complex-uninomials/src/main/scala/org/globalnames/formatters/Positions.scala#L49) if necessary.

**Comment by dimus** [comment]
:+1:  Thanks, I'll continue from here

**Comment by alexander-myltsev** [comment]
@dimus there are reasons to use `{}` for lambdas instead of `()`. So, better to have `u.rank.map { _.typ }`. Alas, I am not always follow it myself. Feel free to correct me when I am not.

**Comment by alexander-myltsev** [comment]
Rest LGTM

**Pull request merged**
