### PR TITLE
Cleanup project

### PR DESCRIPTION
**Pull request by alexander-myltsev**
Bunch of commits to remove unused parts of the project

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
@dimus, please don't merge forawhile. I have some questions.

**Comment by alexander-myltsev** [comment]
Which dependency do you need `resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"` for?

Why do you need `scalacOptions in Test ++= Seq("-Yrangepos")`?

What exactly problems did you meet from [list](http://www.scala-sbt.org/0.13/docs/Running-Project-Code.html) that made you to enable `fork in run := true`?

**Comment by dimus** [comment]
The dependency are coming from Spec2
https://etorreborre.github.io/specs2/website/SPECS2-3.6.2/quickstart.html

I think `fork in run := true` can be safely removed

**Comment by alexander-myltsev** [comment]
Can be merged then.

**Pull request merged**
