### PR TITLE
= Make uninomial (right to 'x' of hybrid formula) implicit

### LINKED ISSUE #53: Fix abbreviated hybrid formula
Currently `Aus x bus` normalizes to `Aus x Aus bus` which is not correct. We need to change rules to normalize to `Aus x bus`

### PR DESCRIPTION
**Pull request by alexander-myltsev**
fix #53

### CODE REVIEW

**Comment by alexander-myltsev** [comment]
@dimus , would you add a test to `test_data` that is closer to life than `"Aus x bus"`?

**Comment by dimus** [comment]
I think the word would be `implied` not implicited
However, we are kind of overloading semantic meaning of implicit from Scala, which might be confusing for people who read the code, may be it would be more clear to say `hidden` or `empty`?

**Comment by dimus** [comment]
we do have tests for it already -- 
```
#Asplenium X inexpectatum (E.L. Braun 1940) Morton (1956)|{"scientificName":{"id":"d37e04e4-90bc-5031-b91c-dbb61113bcfa", "parsed":true, "parser_version":"test_version", "verbatim":"Asplenium X inexpectatum (E.L. Braun 1940) Morton (1956)","normalized":"Asplenium \u00d7 inexpectatum (E. L. Braun 1940) Morton 1956","canonical":"Asplenium \u00d7 inexpectatum", "hybrid":true, "virus": false, "details":[{"genus":{"string":"Asplenium"},"species":{"string":"inexpectatum","authorship":"(E. L. Braun 1940) Morton (1956)","combinationAuthorTeam":{"author":["Morton"],"year":"1956"},"basionymAuthorTeam":{"author":["E. L. Braun"],"year":"1940"}}}],"positions":{"0":["genus",9],"12":["species",24],"26":["author_word",30],"31":["author_word",36],"37":["year",41],"43":["author_word",49],"51":["year",55]}}}
#Mentha ×smithiana R. A. Graham 1949|{"scientificName":{"id":"24188261-3dd9-5173-b94c-f3ad7b145867", "parsed":true, "parser_version":"test_version", "verbatim":"Mentha \u00d7smithiana R. A. Graham 1949","normalized":"Mentha \u00d7 smithiana R. A. Graham 1949","canonical":"Mentha \u00d7 smithiana", "hybrid":true, "virus": false, "details":[{"genus":{"string":"Mentha"},"species":{"string":"smithiana","authorship":"R. A. Graham 1949","basionymAuthorTeam":{"author":["R. A. Graham"],"year":"1949"}}}],"positions":{"0":["genus",6],"8":["species",17],"18":["author_word",20],"21":["author_word",23],"24":["author_word",30],"31":["year",35]}}}
#Salix ×capreola Andersson (1867)|{"scientificName":{"id":"9965be0c-0db2-506a-97f7-e709ef950ef7", "parsed":true, "parser_version":"test_version", "verbatim":"Salix \u00d7capreola Andersson (1867)","normalized":"Salix \u00d7 capreola Andersson 1867","canonical":"Salix \u00d7 capreola", "hybrid":true, "virus": false, "details":[{"genus":{"string":"Salix"},"species":{"string":"capreola","authorship":"Andersson (1867)","basionymAuthorTeam":{"author":["Andersson"],"year":"1867"}}}],"positions":{"0":["genus",5],"7":["species",15],"16":["author_word",25],"27":["year",31]}}}
#Salix x capreola Andersson|{"scientificName":{"id":"5780473c-18ac-5386-9c3a-f74bbe426624", "parsed":true, "parser_version":"test_version", "verbatim":"Salix x capreola Andersson","normalized":"Salix \u00d7 capreola Andersson","canonical":"Salix \u00d7 capreola", "hybrid":true, "virus": false, "details":[{"genus":{"string":"Salix"},"species":{"string":"capreola","authorship":"Andersson","basionymAuthorTeam":{"author":["Andersson"]}}}],"positions":{"0":["genus",5],"8":["species",16],"17":["author_word",26]}}}
```

**Comment by dimus** [comment]
`"positions":[["uninomial",0,5],["genus",0,5],["hybrid_char",6,7],["species",8,16],["author_word",17,26]]}}` shows both uninomiall and genus, we need genus only

**Comment by alexander-myltsev** [comment]
Fixed. Please check eligibility of [that line](https://github.com/GlobalNamesArchitecture/gnparser/pull/94/files#diff-0e179397b4e0644953f3d9373cfcf6cfR32).

**Pull request merged**
